- lib/core/device.rb
Before, when running a Condition before clicking, waiting, or any other action, if the Strategy or Id were a variable, then it will omit the transformation. This pull request fixes that
> convert values before running anything so variables are passed correctly

- lib/core/device.rb
- lib/core/device_handler.rb
- lib/platforms/android.rb
When creating two drivers for android and ios then the latest to be created will overwrite the methods of the other. When thay have shared naming pattern:
```
module Device
module Screen
def self.add_methods
::Appium::Core::Device.add_endpoint_method(:start_recording_screen) do
def start_recording_screen(remote_path: nil, user: nil, pass: nil, method: 'PUT',
file_field_name: nil, form_fields: nil, headers: nil, force_restart: nil,
video_type: 'mjpeg', time_limit: '180', video_quality: nil,
video_fps: nil, video_scale: nil, video_filters: nil, pixel_format: nil)
option = ::Appium::Core::Base::Device::ScreenRecord.new(
remote_path: remote_path, user: user, pass: pass, method: method,
file_field_name: file_field_name, form_fields: form_fields, headers: headers,
force_restart: force_restart …
```
> fix recording bug when using both platforms

- lib/core/device_handler.rb
- lib/core/types_control_flow.rb
With the help of @TDL-EdgarsEglitis now it is possible to pass:
1) vars as value under Type: case;
2) driver_port from config_caps, overwriting default hardcoded values for parallel testing;
3) server_port from ENV var with "serverPort" key.
> config_caps + control_flow update

- .gitignore
- examples/tests/cases/case_ios_tests.yaml
- examples/tests/cases/config.yaml
- lib/platforms/ios.rb
Right now the implementation of TestRay requires that the iOS devices should be real ones, and it doesn't let run in simulators.
With this fix it allows to run on simulators, and it also fixes a bug related to using parenthesis on the name of the devices.
> fix for running on apple simulators

- lib/core/appium_server.rb
In order to be able work with appium 1.X and 2.X the best option is to add the base path, this way we can have backwards compatibility.
> fix url base path for appium 2.x version

- examples/tests/cases/case_av_example.yaml
- lib/core/device_drivers.rb
- testray.gemspec
Right now, using selenium grid 4.14.1 Testray doesnt work, adding this upgrade will make it work.
> add 4. selenium version to get compatibility with Selenium Grid 4.

- README.md
- lib/core/device.rb
Fixes #42 
Also changes the Android versions of these methods to use the execute method extension instead.
> fix: remove app management methods without app ID

- lib/core/device.rb
> fix: replace touchactions with w3c action chains

- lib/core/device.rb
Fixes a few long-standing issues.
> fix: speed up click, avoid conversion in loop

- examples/tests/cases/case_swipe.yaml
- lib/core/appium_server.rb
> fix: appium server shut down

- lib/core/device_handler.rb
Fixes an error created while raising an error about not enough connected devices.
> fix: adjust variable name in error message

- README.md
- lib/core/device.rb
This adds new parameters to the `click` action: `OffsetFractionX` and `OffsetFractionY`, which allow specifying a relative offset, as multipliers of the element width or height, respectively.
Additionally, it is no longer required to provide *both* `OffsetX` and `OffsetY` for absolute offsets - if only one axis is needed, the other parameter can be omitted.
> feat: support fractional offsets in click action

- lib/testray.rb
This adds a simple method to return the TestRay version when running `testray version`.
> feat: add command to return TestRay version

- README.md
- lib/core/device.rb
This adds a new method to make it easier to handle iOS native alerts. It [sets the active app to springboard](https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard) and looks for an element with `class` `XCUIElementTypeAlert`:
* If alert is not found, do nothing
* If alert is found, click on the button specified by `Strategy`/`Id`
For both cases, in the end, the active app is set back to the application under test.
> feat: add method to handle iOS native alerts

- README.md
- lib/core/device.rb
This adds a new method to update the Appium settings. The method accepts a JSON object, which can also be provided as a TestRay var.
> feat: add update_settings type

- README.md
- lib/core/device.rb
This adds a method for an arbitrary swipe over a single element. Similarly to #53 for clicks, the swipe offsets can be provided either in absolute or fractional values.
> feat: add method to swipe on element

- README.md
- lib/core/device.rb
This is a fix to `scroll_until_element_visible` due to its parameter values for offsets not being aligned to those used in other methods (`click` and `swipe_on_element`). In the current implementation, the offsets are measured from the element start point, whereas in the other existing methods, offsets are measured from the element midpoint.
This changes the offset measurement for `scroll_until_element_visible` to also be measured from the element midpoint.
> fix: align scroll_until_element_visible offset params

- README.md
- lib/core/device.rb
This fixes an issue with `scroll_until_element_visible` when using `RecheckAfterScrolls`, where the scroll positions were not correctly calculated. Related to #61.
> fix: fixes for scroll_until_element_visible

- lib/core/device.rb
The `Value` parameter for `launch_app`/`terminate_app` could not be passed as a parameter. Now it can be.
> fix: convert value for launch_app/terminate_app

- lib/core/device.rb
The current implementation for `close_app` is deprecated. This PR updates it to the latest syntax using execute methods, and removes the deprecation warning.
> fix: update close_app implementation

- lib/core/device.rb
This fixes a fairly specific issue with click actions (where multiple timestamps are generated while finding the element):
If the timeout for finding the element (`Time`) is specified to be longer than the timeout for clicking the element (`CheckTime` or the default timeout), there may be a situation where the element search does end up taking a long time - longer than the timeout for clicking the element. This would mean that the condition `while (Time.now - start) < wait_time` would immediately fail, the click action would not even be attempted, and the test would continue.
This PR fixes the issue by adjusting the above condition.
> fix: prevent click action from being skipped

- lib/core/logger.rb
This is the default log format for some other loggers, should not hurt to add it here, it helped to debug some issues with specific scenarios where strict timestamp calculations by step execution are needed later for post processing.
I can also make it an option if you want, but again , it is not a breaking change and shouldn't hurt anything if added as is.
> feat: use milliseconds in log timestamps
